version: '3.7'

services:

  app:
    build: 
      context: ./hackernews
      dockerfile: Dockerfile.prod        
    command: gunicorn --bind 0.0.0.0:8000 manage:app
    image: app
    container_name: app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG=0
    depends_on:
      - redis

  worker:
    image: app
    command: python manage.py run_worker
    env_file:
      - ./.env.prod
    environment:
      - REDIS_URL=redis://redis:6379
      - FLASK_CONFIG=production
      - FLASK_DEBUG=0
    depends_on:
      - app
      - redis

  scheduler:
    image: app
    command: python manage.py run_scheduler
    env_file:
      - ./.env.prod
    environment:
      - REDIS_URL=redis://redis:6379
      - FLASK_CONFIG=production
      - FLASK_DEBUG=0
    depends_on:
      - app
      - redis

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod      

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    depends_on:
      - db


volumes:
  postgres_data: